# Generated by Django 4.2.7 on 2023-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_auth_app', '0003_alter_utilisateur_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone'),
        ),
    ]
