# Generated by Django 4.2.7 on 2023-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_auth_app', '0004_utilisateur_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='department',
            field=models.CharField(choices=[('ADM', 'Administration'), ('COM', 'Commercial'), ('SUP', 'Support'), ('GES', 'Gestion'), ('TST', 'Test')], default='COM', max_length=3, verbose_name='département'),
        ),
    ]
