# Generated by Django 4.2.7 on 2023-12-01 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commercial_assigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Assigné'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_commercial', to=settings.AUTH_USER_MODEL, verbose_name='contact commercial chez Epic Events'),
        ),
    ]
