# Generated by Django 4.2.7 on 2023-11-27 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epic_clients_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_contracts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant restant')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic_clients_app.client', verbose_name='Client')),
                ('sales_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Contact commercial')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
