# Generated by Django 4.2.7 on 2023-11-27 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epic_contracts_app', '0002_contrat_delete_contract'),
        ('epic_events_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de fin')),
                ('lieu', models.CharField(max_length=255, verbose_name='lieu')),
                ('type_evenement', models.CharField(max_length=255, verbose_name="type d'événement")),
                ('statut', models.CharField(choices=[('PL', 'Planifié'), ('RE', 'Réalisé'), ('AN', 'Annulé')], default='PL', max_length=2, verbose_name='statut')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='epic_contracts_app.contrat', verbose_name='contrat associé')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
