# Generated by Django 4.2.7 on 2023-11-29 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_events_app', '0002_evenement_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_geres', to=settings.AUTH_USER_MODEL, verbose_name='gestionnaire'),
        ),
    ]
