# Generated by Django 4.2.7 on 2023-12-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_events_app', '0003_evenement_gestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_invites',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre d'invités"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'department': 'SUPPORT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_geres', to=settings.AUTH_USER_MODEL, verbose_name='gestionnaire'),
        ),
    ]
